// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSRnQy1lunzqddkXGjRXI6GV_fVxIEKzI',
    appId: '1:691727788961:web:46b914066f5f5620d0b9e0',
    messagingSenderId: '691727788961',
    projectId: 'vraz-5de39',
    authDomain: 'vraz-5de39.firebaseapp.com',
    storageBucket: 'vraz-5de39.firebasestorage.app',
    measurementId: 'G-CWJW75FRQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-erptz1If6sFeAdq2gnQ6kXcusy8s6Ys',
    appId: '1:691727788961:android:5036a5c6bb9bb1a4d0b9e0',
    messagingSenderId: '691727788961',
    projectId: 'vraz-5de39',
    storageBucket: 'vraz-5de39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqmh1suwB0iJrCUsCF25jKR3a5ulS5GU',
    appId: '1:691727788961:ios:a06ef2541499c909d0b9e0',
    messagingSenderId: '691727788961',
    projectId: 'vraz-5de39',
    storageBucket: 'vraz-5de39.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqmh1suwB0iJrCUsCF25jKR3a5ulS5GU',
    appId: '1:691727788961:ios:a06ef2541499c909d0b9e0',
    messagingSenderId: '691727788961',
    projectId: 'vraz-5de39',
    storageBucket: 'vraz-5de39.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSRnQy1lunzqddkXGjRXI6GV_fVxIEKzI',
    appId: '1:691727788961:web:21a10a4842d40ac5d0b9e0',
    messagingSenderId: '691727788961',
    projectId: 'vraz-5de39',
    authDomain: 'vraz-5de39.firebaseapp.com',
    storageBucket: 'vraz-5de39.firebasestorage.app',
    measurementId: 'G-0H494DNCZ6',
  );
}
